apiVersion: v2
name: k8s-sec-stack
description: OSS Kubernetes security stack — posture, VM, and runtime threats
type: application
version: 0.1.0

dependencies:
  - name: falco
    version: "8.0.5"
    repository: https://falcosecurity.github.io/charts
    condition: falco.enabled

  - name: falcosidekick
    version: "0.13.1"
    repository: https://falcosecurity.github.io/charts
    condition: falcosidekick.enabled

  - name: trivy-operator
    version: "0.32.1"
    repository: https://aquasecurity.github.io/helm-charts
    condition: trivyOperator.enabled

  - name: kubescape-operator
    version: "1.40.2"
    repository: https://kubescape.github.io/helm-charts
    condition: kubescapeOperator.enabled

  - name: kyverno
    version: "3.8.1"
    repository: https://kyverno.github.io/kyverno
    condition: kyverno.enabled
