apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: Pod Security - Baseline
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Privilege escalation allows a process to gain more privileges than its
      parent. This policy audits containers that do not explicitly set
      allowPrivilegeEscalation: false.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: privilege-escalation
      match:
        any:
          - resources:
              kinds: [Pod]
      exclude:
        any:
          - resources:
              namespaces: [kube-system, kube-public, kube-node-lease, security, kubescape]
      validate:
        message: "Privilege escalation must be explicitly disabled."
        pattern:
          spec:
            =(initContainers):
              - securityContext:
                  allowPrivilegeEscalation: "false"
            containers:
              - securityContext:
                  allowPrivilegeEscalation: "false"
