apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-event-sink-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
